// GET  /api/crm/contratos?key=...&cliente_id=...
// POST /api/crm/contratos?key=...  body: contrato fields
//
// On POST: automatically generates the first fatura (or all parcelas if recorrencia=Parcelado).

export async function onRequestGet(context) {
  const { request, env } = context;
  const url = new URL(request.url);
  if (!auth(url, env)) return json({ error: 'Unauthorized' }, 401);

  const cliente_id = url.searchParams.get('cliente_id') || '';

  try {
    const rows = cliente_id
      ? await env.DB.prepare(
          'SELECT * FROM crm_contratos WHERE cliente_id = ? ORDER BY created_at DESC'
        ).bind(cliente_id).all()
      : await env.DB.prepare(
          'SELECT * FROM crm_contratos ORDER BY created_at DESC LIMIT 200'
        ).all();

    return json({ contratos: rows.results || [] });
  } catch (err) {
    return json({ error: err.message }, 500);
  }
}

export async function onRequestPost(context) {
  const { request, env } = context;
  const url = new URL(request.url);
  if (!auth(url, env)) return json({ error: 'Unauthorized' }, 401);

  let body;
  try { body = await request.json(); } catch { return json({ error: 'Invalid JSON' }, 400); }

  const {
    cliente_id, valor, recorrencia = 'Único', moeda = 'BRL',
    data_inicio, vencimento, dia_vencimento, num_parcelas,
    comissao_estimada, forma_pagamento_prevista,
  } = body;

  if (!cliente_id) return json({ error: 'cliente_id is required' }, 400);
  if (!valor || valor <= 0) return json({ error: 'valor must be positive' }, 400);

  const id  = crypto.randomUUID();
  const now = Math.floor(Date.now() / 1000);

  try {
    await env.DB.prepare(`
      INSERT INTO crm_contratos
        (id, cliente_id, valor, recorrencia, data_inicio, vencimento,
         status, moeda, dia_vencimento, num_parcelas,
         comissao_estimada, forma_pagamento_prevista, created_at, updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    `).bind(
      id, cliente_id, valor, recorrencia,
      data_inicio || null, vencimento || null,
      'Ativo', moeda,
      dia_vencimento ?? null,
      num_parcelas ?? null,
      comissao_estimada ?? null,
      forma_pagamento_prevista ?? null,
      now, now,
    ).run();

    // auto-generate faturas
    const faturas = buildFaturas(
      id, cliente_id, valor, moeda, recorrencia, data_inicio, num_parcelas,
      comissao_estimada, forma_pagamento_prevista,
    );
    if (faturas.length) {
      const stmt = env.DB.prepare(`
        INSERT OR IGNORE INTO crm_faturas
          (id, cliente_id, contrato_id, mes, valor, comissao, forma_pagamento, status, created_at, updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?)
      `);
      await env.DB.batch(faturas.map(f =>
        stmt.bind(f.id, f.cliente_id, f.contrato_id, f.mes, f.valor, f.comissao ?? null, f.forma_pagamento ?? null, f.status, now, now)
      ));
    }

    const contrato = await env.DB.prepare('SELECT * FROM crm_contratos WHERE id = ?').bind(id).first();
    return json({ contrato, faturas_geradas: faturas.length, faturas }, 201);
  } catch (err) {
    return json({ error: err.message }, 500);
  }
}

export async function onRequestOptions() {
  return new Response(null, { status: 204, headers: corsHeaders() });
}

// ── fatura generation ─────────────────────────────────────────────────────────

function buildFaturas(contrato_id, cliente_id, valor, moeda, recorrencia, data_inicio, num_parcelas, comissao_estimada, forma_pagamento_prevista) {
  const base = data_inicio ? new Date(data_inicio) : new Date();
  const faturas = [];

  if (recorrencia === 'Único') {
    faturas.push(makeFatura(contrato_id, cliente_id, valor, base, comissao_estimada, forma_pagamento_prevista));
  } else if (recorrencia === 'Parcelado' && num_parcelas > 0) {
    const comissaoParcela = comissao_estimada != null ? comissao_estimada / num_parcelas : null;
    for (let i = 0; i < num_parcelas; i++) {
      const d = addMonths(base, i);
      faturas.push(makeFatura(contrato_id, cliente_id, valor / num_parcelas, d, comissaoParcela, forma_pagamento_prevista));
    }
  } else if (recorrencia === 'Mensal') {
    // generate just the current month; future months auto-generated by cron (future scope)
    faturas.push(makeFatura(contrato_id, cliente_id, valor, base, comissao_estimada, forma_pagamento_prevista));
  }
  // Trimestral / Anual: generate the first one only — keep it simple
  else {
    faturas.push(makeFatura(contrato_id, cliente_id, valor, base, comissao_estimada, forma_pagamento_prevista));
  }

  return faturas;
}

function makeFatura(contrato_id, cliente_id, valor, date, comissao = null, forma_pagamento = null) {
  const mes = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
  return {
    id: crypto.randomUUID(), cliente_id, contrato_id, mes, valor,
    comissao: comissao ?? null, forma_pagamento: forma_pagamento ?? null,
    status: 'pendente',
  };
}

function addMonths(date, n) {
  const d = new Date(date);
  d.setMonth(d.getMonth() + n);
  return d;
}

// ── helpers ───────────────────────────────────────────────────────────────────

function auth(url, env) {
  return env.DASH_KEY && url.searchParams.get('key') === env.DASH_KEY;
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders() },
  });
}

function corsHeaders() {
  return { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type' };
}
