-- CRM tables: leads, clientes, contratos, faturas, tarefas, despesas
-- Adapted from blueprint for D1 (SQLite): UUID→TEXT, JSONB→TEXT, numeric→REAL, timestamp→INTEGER (unix seconds), date→TEXT 'YYYY-MM-DD'
-- All tables prefixed crm_ to avoid collisions with tracking tables.
-- Nicho agência de viagens: extra fields destino + data_viagem on leads; tipo = Pacote/Seguro/Hotel; recorrencia default Único.

CREATE TABLE IF NOT EXISTS crm_leads (
  id              TEXT    PRIMARY KEY,
  nome            TEXT    NOT NULL,
  nicho           TEXT,
  proj            TEXT,
  status          TEXT    NOT NULL DEFAULT 'novo',     -- novo | contato | proposta | fechado | perdido
  valor_estimado  REAL,
  moeda           TEXT    NOT NULL DEFAULT 'BRL',      -- BRL | USD | EUR
  tipo            TEXT,                                -- Pacote | Seguro | Hotel
  destino         TEXT,                                -- agência: destino de viagem
  data_viagem     TEXT,                                -- agência: 'YYYY-MM-DD'
  followup        TEXT,                                -- 'YYYY-MM-DD'
  obs             TEXT,
  contato_data    INTEGER,                             -- unix seconds
  cliente_id      TEXT,                                -- set after conversion → crm_clientes.id
  session_id      TEXT,                                -- optional link → sessions.session_id
  event_log_id    INTEGER,                             -- optional link → event_log.id
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS crm_clientes (
  id              TEXT    PRIMARY KEY,
  nome            TEXT    NOT NULL,
  empresa         TEXT,
  instagram       TEXT,
  email           TEXT,
  telefone        TEXT,
  proj            TEXT,
  status          TEXT    NOT NULL DEFAULT 'Ativo',    -- Ativo | Inativo
  como_conheceu   TEXT,                                -- Feiras | Parceiros | Google Ads | Instagram | Indicação
  observacao      TEXT,
  lead_id         TEXT,                                -- nullable → crm_leads.id
  av              TEXT,                                -- initials avatar, generated by frontend
  cidade          TEXT,
  estado          TEXT,
  pais            TEXT,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS crm_contratos (
  id              TEXT    PRIMARY KEY,
  cliente_id      TEXT    NOT NULL,                    -- → crm_clientes.id
  valor           REAL    NOT NULL,
  recorrencia     TEXT    NOT NULL DEFAULT 'Único',    -- Mensal | Trimestral | Anual | Único | Parcelado
  data_inicio     TEXT,                                -- 'YYYY-MM-DD'
  vencimento      TEXT,                                -- 'YYYY-MM-DD'
  status          TEXT    NOT NULL DEFAULT 'Ativo',    -- Ativo | Inativo
  moeda           TEXT    NOT NULL DEFAULT 'BRL',
  dia_vencimento  INTEGER,                             -- 1-31, fixed billing day
  num_parcelas    INTEGER,                             -- set when recorrencia = Parcelado
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS crm_faturas (
  id              TEXT    PRIMARY KEY,
  cliente_id      TEXT    NOT NULL,                    -- → crm_clientes.id
  contrato_id     TEXT    NOT NULL,                    -- → crm_contratos.id
  mes             TEXT    NOT NULL,                    -- 'YYYY-MM'
  valor           REAL    NOT NULL,
  status          TEXT    NOT NULL DEFAULT 'pendente', -- pago | pendente | vencido
  data_pagamento  TEXT,                                -- 'YYYY-MM-DD', null until paid
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE (cliente_id, mes)                             -- one invoice per client/month; upsert pattern
);

CREATE TABLE IF NOT EXISTS crm_tarefas (
  id              TEXT    PRIMARY KEY,
  cliente_id      TEXT,                                -- nullable → crm_clientes.id
  titulo          TEXT    NOT NULL,
  obs             TEXT,
  status          TEXT    NOT NULL DEFAULT 'a-fazer',  -- a-fazer | andamento | revisao | concluido
  data_inicio     TEXT,                                -- 'YYYY-MM-DD'
  data_entrega    TEXT,                                -- 'YYYY-MM-DD'
  checklist       TEXT,                                -- JSON: [{item: string, done: boolean}]
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at      INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS crm_despesas (
  id              TEXT    PRIMARY KEY,
  item            TEXT    NOT NULL,
  valor           REAL    NOT NULL,
  periodo         TEXT    NOT NULL DEFAULT 'Único',    -- Mensal | Único
  categoria       TEXT,                                -- Infraestrutura | Marketing | etc.
  data            TEXT    NOT NULL,                    -- 'YYYY-MM-DD'
  data_fim        TEXT,                                -- 'YYYY-MM-DD', nullable
  created_at      INTEGER NOT NULL DEFAULT (unixepoch())
);

-- indexes
CREATE INDEX IF NOT EXISTS idx_crm_leads_status   ON crm_leads(status);
CREATE INDEX IF NOT EXISTS idx_crm_leads_followup  ON crm_leads(followup);
CREATE INDEX IF NOT EXISTS idx_crm_leads_created   ON crm_leads(created_at);
CREATE INDEX IF NOT EXISTS idx_crm_clientes_status ON crm_clientes(status);
CREATE INDEX IF NOT EXISTS idx_crm_contratos_cli   ON crm_contratos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_crm_faturas_status  ON crm_faturas(status, mes);
CREATE INDEX IF NOT EXISTS idx_crm_faturas_mes     ON crm_faturas(mes);
CREATE INDEX IF NOT EXISTS idx_crm_tarefas_status  ON crm_tarefas(status);
CREATE INDEX IF NOT EXISTS idx_crm_tarefas_cliente ON crm_tarefas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_crm_despesas_data   ON crm_despesas(data);
