CREATE TABLE proposals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lead_id INTEGER,
  client_name TEXT DEFAULT '',
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'draft',
  destinations TEXT NOT NULL DEFAULT '[]',
  travel_start TEXT,
  travel_end TEXT,
  travelers INTEGER DEFAULT 1,
  hotels TEXT DEFAULT '[]',
  flights TEXT DEFAULT '[]',
  price_total REAL,
  price_per_person REAL,
  currency TEXT DEFAULT 'BRL',
  includes TEXT DEFAULT '',
  excludes TEXT DEFAULT '',
  payment_info TEXT DEFAULT '',
  internal_cost REAL,
  internal_notes TEXT DEFAULT '',
  cover_images TEXT DEFAULT '[]',
  description TEXT DEFAULT '',
  cta_primary_label TEXT DEFAULT 'Quero reservar',
  cta_primary_url TEXT DEFAULT '',
  cta_secondary_label TEXT DEFAULT 'Tenho dúvidas',
  cta_secondary_url TEXT DEFAULT '',
  itinerary TEXT DEFAULT '[]',
  expires_at TEXT,
  views INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
